name: dot_mall_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  path: ^1.8.0
  dio:
  recase:
  inflection3: ^0.5.3+2
  source_gen:
  build:
  # annotations:
  #   path: ../annotations/

dev_dependencies:
  build_runner:
  build_test:
  lints: ^2.0.0
  test: ^1.16.0
