name: auto_sdk_annotations
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  code_builder: ^4.2.0
  dio:
  recase:
  inflection3: ^0.5.3+2
  auto_sdk_core:
    path: ../auto_sdk_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
