name: generator
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  path: ^1.8.0
  code_builder: ^4.2.0
  dart_style: ^2.2.3
  dio:
  recase:
  inflection3: ^0.5.3+2
  source_gen: ^1.2.2


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
