name: auto_sdk_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'


dependencies:
  path: ^1.8.0
  source_gen: ^1.2.2
  build:
  dotmall_sdk:
    path: ../
  auto_sdk_annotations:
    path: ../auto_sdk_annotations
  code_builder: ^4.2.0
  dio:
  recase:
  inflection3: ^0.5.3+2
  dart_style:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0
