name: auto_sdk
description: auto sdk is a tool to generate sdk
version: 0.0.1-dev
homepage: https://github.com/physia/auto_sdk
repository: https://github.com/physia/auto_sdk

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
