name: auto_sdk_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  path: ^1.8.0
  dio: ^4.0.6
  recase: ^4.0.0
  inflection3: ^0.5.3+2
  source_gen: ^1.2.2
  auto_sdk_annotations:
    path: ../auto_sdk_annotations
  auto_sdk_generator:
    path: ../auto_sdk_generator
  code_builder: ^4.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0

