name: dotmall
description: Dotmall
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  recase: ^4.0.0
  google_fonts: ^3.0.1
  fluentui_system_icons: ^1.1.176
  shared_preferences: ^2.0.15
  animations: ^2.0.3
  dio: ^4.0.6
  equatable: ^2.0.3
  routemaster: ^1.0.1
  hive: ^2.2.3
  collection: ^1.16.0
  dotmall_sdk:
    path: ./packeges/dotmall_sdk

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1
  flutter_launcher_icons: "^0.9.2"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/SVG/
    - assets/images/1000w/
    - assets/images/200w/

