name: dotmall_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  dio:
  recase:
  inflection3: ^0.5.3+2
  source_gen: ^1.2.2
  auto_sdk_annotations:
    path: auto_sdk_annotations
  auto_sdk_generator:
    path: auto_sdk_generator
  auto_sdk_core:
    path: auto_sdk_core
  code_builder: ^4.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.2.0


scripts:
  build:
    - cd example && run build_runner build